events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 8000;


        # 📍 2. API สำหรับ Auth (ใช้ทางนี้ทางเดียวเท่านั้น!)
        location /api/auth/ {
            proxy_pass http://authentication-service:8082;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 📍 3. API สำหรับ Discussion
        location /api/posts {
            proxy_pass http://discussion-service:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 📍 4. API สำหรับ Moderation
        location /api/tasks {
            proxy_pass http://moderation-service:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # 🌟 4. API สำหรับ Health Check & Metrics (เพิ่มใหม่ตรงนี้!)
        # --- ตู้ Auth ---
        location /auth/health {
            proxy_pass http://authentication-service:8082/health;
        }
        location /auth/metrics {
            proxy_pass http://authentication-service:8082/metrics;
        }

        # --- ตู้ Discussion ---
        location /disc/health {
            proxy_pass http://discussion-service:8080/health;
        }
        location /disc/metrics {
            proxy_pass http://discussion-service:8080/metrics;
        }

        # --- ตู้ Moderation ---
        location /mod/health {
            proxy_pass http://moderation-service:8081/health;
        }
        location /mod/metrics {
            proxy_pass http://moderation-service:8081/metrics;
        }

        location / {
            root /usr/share/nginx/html;
            index login.html;
            try_files $uri $uri/ /login.html;
        }
        
    }
}