global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 

  - job_name: 'consul_discovery'
    consul_sd_configs:
      - server: 'consul:8500' 
    relabel_configs:
      - source_labels: [__meta_consul_service]
        regex: '.*-service.*'
        action: keep

  # <-- ADDED: Force it to scrape RabbitMQ Queue Depth
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']